__author__ = "Jia Jia"
__author_email__ = "angersax@sina.com"
__description__ = "PingView API"
__license__ = "Apache-2.0"
__title__ = "api"
__url__ = "https://github.com/pingview/api"
__version__ = "1.0.0"
